### ISSUE TITLE
"An error occurred in the current transaction" when encountering duplicate (?) notification

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot-plugin-circuit-maintenance#107]
### Environment

- Python version: 
- Nautobot version: 1.1.2
- nautobot-circuit-maintenance version: 0.2.3

### Expected Behavior

Circuit maintenance job to run to completion and successfully process notifications, including those that have already been processed.

### Observed Behavior

![image](https://user-images.githubusercontent.com/5603551/133852906-30534340-231f-4670-8d1c-e907994a0636.png)

### Steps to Reproduce

I'm not sure. Even after deleting all pre-existing RawNotification records, I'm encountering this issue, but it does *not* appear that I actually have two duplicate emails (same exact datestamp, subject, and provider) in my inbox, so I don't understand how we're even triggering this condition.

I do have multiple emails from the same provider with the same subject line, but they have different `Date:` stamps on them.

**Comment by glennmatthews** [comment]
Also worth noting that when this condition is encountered, it appears to cause the database to rollback the entire job's changes - when the job completes, there are no new database entries present, even for those notifications that were processed before the error was triggered.

**Comment by chadell** [comment]
I have been able to replicate in my DEV environment, so hopefully it would be solved sooner than later.

**Comment by chadell** [comment]
Test to reproduce it: 60dbb8833538dde11790f1c728427ceaeff577a1

**Comment by glennmatthews** [comment]
Fixed by #108. Thanks!
