### ISSUE TITLE
Increase default `rawnotification` `raw` size to capture at lease email headers

### ISSUE THREAD

**Issue by chadell** [nautobot/nautobot-plugin-circuit-maintenance#116]
### Environment

- Python version: 3.x
- Nautobot version: 1.1.2
- nautobot-circuit-maintenance version: 0.2.4

### Expected Behavior

We should be able to get the basic info from an original email when stored in the `rawnotification.raw` field. This data is truncated by default to 500 characters 

### Observed Behavior

This truncation means missing basic email headers information, so we should look for a value (8192?) that consistently give enough information in the headers to locate the notification in the email source box.

### Steps to Reproduce

1.
2.
3.

**Comment by glennmatthews** [comment]
In many cases neither the end user nor the parser care that much about the details of the email's headers - it would be more useful to specifically capture the parts of the email that are actually used by the parser, i.e. the subject line, sender address, and most importantly the email's actual body content.

**Comment by chadell** [comment]
Changed in #127
