### ISSUE TITLE
Improve Documentation

### ISSUE THREAD

**Issue by nniehoff** [nautobot/nautobot-plugin-circuit-maintenance#12]
### Environment

- Python version: 3.6
- Nautobot version: 1.0.1
- nautobot-circuit-maintenance version: 0.1.1

In the add notifications form I am prompted for a Url with no description and source type is either gmail or unknown.  A minimal description of the Url field and some documentation around configuring other email sources would be very beneficial.

### Expected Behavior

The documentation should provide examples for configuring a POP3 or an IMAP mail server at a minimum.

### Observed Behavior

Documentation refers to URL but nothing further

**Comment by chadell** [comment]
fixed in #13
