### ISSUE TITLE
GMail integration: optionally tag/categorize emails when successfully parsed.

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot-plugin-circuit-maintenance#120]
### Environment

- Nautobot version: 
- nautobot-circuit-maintenance version: 

### Proposed Functionality

In the GMail integration, it would be very useful to tag processed emails with one or more categories after processing them, e.g. "parsed" and "parse_failed" perhaps.

### Use Case

This makes it easier for the developer or user to filter the service inbox to see which messages were processed, skipped, and/or failed parsing for troubleshooting and data accuracy checking.

**Comment by chadell** [comment]
Something like this was explored for issue #71 and as tested [here](https://github.com/nautobot/nautobot-plugin-circuit-maintenance/pull/50/files#diff-2d57fdbc7bef42b62edc901fb5776819412661f25721b7b69428005c77fc2723R549) it only requires as biggest change, enabling a new scope to "write".
