### ISSUE TITLE
Update documentation to mention 'nautobot-server post_upgrade'

### ISSUE THREAD

**Issue by ozmusic** [nautobot/nautobot-plugin-circuit-maintenance#181]
### Environment

- Nautobot version: 1.2.3
- nautobot-circuit-maintenance version: 0.5.0

Update to FAQ or readme to include step for run 'nautobot-server post_upgrade' after adding a notification source to nautobot_config.py 

### Proposed Functionality

Between step 2.1.2.3 and 2.2 mention of the readme, mention that the admin should run 'nautobot-server post_upgrade'

### Use Case

The readme currently assumes the user knows to run the post_upgrade command after changing nautobot_config.py. Including this step as part of the configuration guide will remove the assumed knowledge.

**Comment by chadell** [comment]
@ozmusic , documentation updated. Thanks for reporting!
