### ISSUE TITLE
General Dashboard Page

### ISSUE THREAD

**Issue by jvanderaa** [nautobot/nautobot-plugin-circuit-maintenance#189]
### Environment
 Current

### Proposed Functionality

I would like to implement a dashboard page that would give I believe the following stats:

- Upcoming maintenances in the next 7 days
- Number of maintenances completed in the past 7/30/365 days
- Average duration of planned maintenances
- Outstanding maintenances (upcoming)
- Average Number of Maintenances per circuit per calendar year
- Average maintenances per month per carrier

**Comment by chadell** [comment]
I like this summary/report!

**Comment by jvanderaa** [comment]
I have been testing a few views out. I may need a small bit of work yet but have something later this week.

**Comment by jvanderaa** [comment]
This is where I'm at so far on the progress. 

- [ ] Finish the rest of the calculations
- [ ] Move calculations into generic function so they can be exposed via Capacity Metrics

![Screen Shot 2022-07-04 at 17 03 00](https://user-images.githubusercontent.com/22228848/177220681-c1d110bd-2294-426a-b836-10dbe6d16b12.png)

**Comment by chadell** [comment]
I like the idea to extend the capacity metrics with more data and expose it to observability.

**Comment by chadell** [comment]
Implemented in #191
