### ISSUE TITLE
Missing Side when Provider Network

### ISSUE THREAD

**Issue by jvanderaa** [nautobot/nautobot-plugin-circuit-maintenance#198]
### Environment
Development

### Expected Behavior

Expected to show a Z side connection

### Observed Behavior

No Z Side connection

### Steps to Reproduce

1. Create a bunch of circuits, with an A-side that is at a site, Z-side that is a Provider Network
2. Create a circuit maintenance impacting the circuit
3. Go to the maintenance record, look for Z-Side, which then shows `None`

**Comment by FragmentedPacket** [comment]
Looked into this and it appears it's just an issue in the `circuitmaintenance.html` template.

It was:

```
                   <td>
                        {{ circuit.circuit.termination_a.site }}
                    </td>
                    <td>
                        {{ circuit.circuit.termination_z.site }}
                    </td>
```

This is just updating logic to account for the potential termination types currently supported.

```
                   <td>
                    {% if circuit.circuit.termination_a.site %}
                        {{ circuit.circuit.termination_a.site }}
                    {% elif circuit.circuit.termination_a.location %}
                        {{ circuit.circuit.termination_a.location }}
                    {% elif circuit.circuit.termination_a.provider_network %}
                        {{ circuit.circuit.termination_a.provider_network }}
                    {% endif %}
                    </td>
                    <td>
                    {% if circuit.circuit.termination_z.site %}
                        {{ circuit.circuit.termination_z.site }}
                    {% elif circuit.circuit.termination_z.location %}
                        {{ circuit.circuit.termination_z.location }}
                    {% elif circuit.circuit.termination_z.provider_network %}
                        {{ circuit.circuit.termination_z.provider_network }}
                    {% endif %}
                    </td>
```

I can submit a PR if that is an OK fix unless y'all were thinking something different or if there is a potential filter available.

**Comment by chadell** [comment]
@FragmentedPacket thanks!
Yes, it looks like the template is "old", and this code change would fix it.
It would be great to get you as contributor with a PR! and it will give you one PR for the Hacktoberfest!
