### ISSUE TITLE
Move Circuit Maintenance to Circuits TL Menu

### ISSUE THREAD

**Issue by jvanderaa** [nautobot/nautobot-plugin-circuit-maintenance#202]
### Environment

- Nautobot version: 1.4
- nautobot-circuit-maintenance version: For 1.4

### Proposed Functionality

Move the plugin menu navigation to being part of the *Circuits* navigation menu.

https://nautobot.readthedocs.io/en/stable/development/navigation-menu/#modifying-existing-menu

### Use Case

Putting Circuit Maintenance into an area that makes sense.

**Comment by chadell** [comment]
Done
