### ISSUE TITLE
Email Sync - Unable to Create Raw Notification

### ISSUE THREAD

**Issue by jvanderaa** [nautobot/nautobot-plugin-circuit-maintenance#218]
### Environment

- Python version: 
- Nautobot version: 1.4.5
- nautobot-circuit-maintenance version: `develop` branch

### Expected Behavior

* Email parsing of maintenance record to create records

### Observed Behavior

```
Raw notification 'MaintenanceNotification' not created because value too long for type character varying(100)
```

### Steps to Reproduce

1. Create an ICS templated email
2. Sync email
3. Receive the error

**Comment by chadell** [comment]
Newer Nautobot version (1.4.x) adds the `ChangeLoggedModel` to the `OrganizationalModel`, used by `RawNotification` and `ParserNotification`. This causes this issue.
A quick fix is to remove this dependency via: `class RawNotification(BaseModel, CustomFieldModel, RelationshipModel)`
But a proper strategy has to be found to solve for the new versions.

**Comment by chadell** [comment]
The issue comes from the long `change_context_detail`, longer than 100: `plugins-nautobot_circuit_maintenance-handle_notifications-handler-handlecircuitmaintenancenotifications`
