### ISSUE TITLE
Release major release `1.X`

### ISSUE THREAD

**Issue by chadell** [nautobot/nautobot-plugin-circuit-maintenance#239]
### Environment

- Nautobot version: 
- nautobot-circuit-maintenance version: 

### Proposed Functionality

After being running for a while in multiple production environments, release a first major release.

### Use Case

Make clear the plugin usability for production environments.

**Comment by chadell** [comment]
It would be great to have https://github.com/nautobot/nautobot-plugin-circuit-maintenance/pull/227 in

**Comment by jvanderaa** [comment]
I'll get some work on this on Monday to get the python 3.7 support back added into the PR that I had started.

**Comment by chadell** [comment]
released
