### ISSUE TITLE
relocate Circuit Maintenance menu items under Circuit menu 

### ISSUE THREAD

**Issue by jedelman8** [nautobot/nautobot-plugin-circuit-maintenance#248]
### Proposed Functionality 

Not sure this was ever discussed, but it just seems logical to navigate to Circuits -> Circuit Notifications vs. Plugins -> Circuit Notifications.  Assuming URL doesn't change, why not?

**Comment by jvanderaa** [comment]
Will get this in and release a 1.0.0 for this

**Comment by glennmatthews** [comment]
duplicate of #202?

**Comment by chadell** [comment]
This is done
