### ISSUE TITLE
Migrate to Celery from RQ

### ISSUE THREAD

**Issue by chadell** [nautobot/nautobot-plugin-circuit-maintenance#38]
### Environment

- Nautobot version: 1.1.x

### Expected Behavior

Use Celery instead of RQ: https://nautobot.readthedocs.io/en/latest/installation/services/#migrating-to-celery-from-rq

**Comment by glennmatthews** [comment]
I'm not sure there's any actual code change needed here. `Job` classes will transparently switch from running in RQ to running in Celery - we would only need to make changes to the plugin if we have our own custom `django_rq` background worker tasks (i.e. the `@job` decorator), which to the best of my knowledge, we don't?

**Comment by chadell** [comment]
Thanks @glennmatthews , you are right, we were using `from nautobot.extras.jobs import Job`, so it will transparently switch!
