### ISSUE TITLE
More flexible mapping of Provider (Nautobot) to Provider (circuit-maintenance-parser)

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot-plugin-circuit-maintenance#43]
### Environment

- Nautobot version: 
- nautobot-circuit-maintenance version: 

### Proposed Functionality

Mapping Nautobot Providers to circuit-maintenance-provider Provider classes based on the Nautobot Provider `slug` is inflexible as it relies on enforcing that the Nautobot Provider `slug` be exactly equal to the circuit-maintenance-provider Provider class `__name__`. In practice this may not always be the case, and it's not always going to be feasible to change the existing `slug` in Nautobot to resolve this.

### Use Case

I have a Nautobot deployment with circuits defined for provider `CenturyLink` (former name of the provider now called Lumen). Without changing the `slug` of this provider, or creating a new `Lumen` provider and remapping all of the circuits to this new provider, I have no way to make emails from Lumen be handled by the Lumen parser provider because the plugin is looking for a parser called `centurylink`.

**Comment by glennmatthews** [comment]
Maybe another optional custom field on Provider?

**Comment by chadell** [comment]
Addressed in #51
