### ISSUE TITLE
Rendering of `raw` field in a RawNotification detail view could render text

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot-plugin-circuit-maintenance#48]
### Environment

- Nautobot version: 1.0.3
- nautobot-circuit-maintenance version: 0.1.7

### Proposed Functionality

In the common case where a RawNotification's `raw` data is actually a human-readable string, it would be nice to render it as such, instead of as a raw byte-string. I.e., it currently appears like:

![image](https://user-images.githubusercontent.com/5603551/127157662-f2d79c7f-d81b-47c4-9aee-fff838c651e0.png)

but it would be nicer to render the text, for example as:

![image](https://user-images.githubusercontent.com/5603551/127157927-0f60aac4-6f8c-4b45-a5ec-85f0238f0d13.png)

**Comment by chadell** [comment]
Implemente in #55
