### ISSUE TITLE
Custom Fields are not visible in Circuit Maintenance View 

### ISSUE THREAD

**Issue by dgarros** [nautobot/nautobot-plugin-circuit-maintenance#56]
### Environment

- Python version: 3.6
- Nautobot version: 1.1.0
- nautobot-circuit-maintenance version: latest

### Expected Behavior

All custom fields associated with the CircuitMaintenance object should be visible in the CircuitMaintenance detail view.

### Observed Behavior

Custom fields are not visible in the detail view page but they are visible in the edit view

### Steps to Reproduce

1. Create a new custom field and associate it with the CircuitMaintenance model
2. Create a CircuitMaintenance 
3. check the detail view of the newly created circuit maintenance

**Comment by glennmatthews** [comment]
Once Nautobot 1.2 is released, CircuitMaintenance detail view should ideally inherit from `generic/object_detail.html` (https://github.com/nautobot/nautobot/pull/737) so as to pick up custom fields, relationships, etc. automatically. In the short term this will need to be addressed within the local `circuitmaintenance.html` directly.

**Comment by chadell** [comment]
implemented in #61
