### ISSUE TITLE
Custom Fields are not visible in the Raw Notification View

### ISSUE THREAD

**Issue by dgarros** [nautobot/nautobot-plugin-circuit-maintenance#57]
### Environment

- Python version: 3.6
- Nautobot version: 1.1.0
- nautobot-circuit-maintenance version: latest

### Expected Behavior

All custom fields associated with the RawNotification object should be visible in the RawNotification detail view.

### Observed Behavior

Custom fields are not visible in the detail view page 

### Steps to Reproduce

1. Create a new custom field and associate it with the RawNotification model
2. Create a RawNotification (via the ORM)
3. check the detail view of the newly created raw notification

**Comment by glennmatthews** [comment]
As with #56, in the long term this should be addressed by inheriting from generic/object_detail.html in Nautobot 1.2+ (https://github.com/nautobot/nautobot/pull/737).

**Comment by chadell** [comment]
implemented in #61
