### ISSUE TITLE
Relationships are not visible in the Circuit Maintenance View

### ISSUE THREAD

**Issue by dgarros** [nautobot/nautobot-plugin-circuit-maintenance#58]
### Environment

- Python version: 3.6
- Nautobot version: 1.1.0
- nautobot-circuit-maintenance version: latest

### Expected Behavior

All Relationships associated with the CircuitMaintenance object should be visible in the CircuitMaintenance detail view.

### Observed Behavior

User defined Relationships are not visible in the detail view page but they are visible in the edit view

### Steps to Reproduce

1. Create a new relationship and associate it with the CircuitMaintenance model
2. Create a CircuitMaintenance
3. check the detail view of the newly created circuit maintenance

**Comment by glennmatthews** [comment]
As with #56 and #57, in the long term this should be addressed by inheriting from `generic/object_detail.html` in Nautobot 1.2+ (https://github.com/nautobot/nautobot/pull/737).

**Comment by chadell** [comment]
implemented in #61
