### ISSUE TITLE
RawNotification detail view is not rendering properly with a large payload

### ISSUE THREAD

**Issue by dgarros** [nautobot/nautobot-plugin-circuit-maintenance#59]
### Environment

- Python version: 3.6
- Nautobot version: 1.1.0
- nautobot-circuit-maintenance version: latest

### Expected Behavior

RawNotification detail view should render properly for all size of RawNotification payload

### Observed Behavior

![image](https://user-images.githubusercontent.com/304126/128773195-96aab1d3-675b-43eb-bb7a-81f874d01f25.png)

**Comment by glennmatthews** [comment]
Should be addressed by fixing #48, IMO.

**Comment by chadell** [comment]
Yes, as Glenn suggested, #48 is also addressing this issue

**Comment by chadell** [comment]
Implemente in #55
