### ISSUE TITLE
Unable to navigate directly to the circuit maintenance from the Circuit page

### ISSUE THREAD

**Issue by dgarros** [nautobot/nautobot-plugin-circuit-maintenance#60]
### Environment

- Python version: 3.6
- Nautobot version: 1.1.0
- nautobot-circuit-maintenance version: latest

### Expected Behavior

From the detail view of a circuit i should be able to visualize the upcoming maintenances and directly navigate to them by following a link.  

### Observed Behavior

The list of upcoming maintenances is represented in the detail view of a circuit on the left but there is no link to the corresponding object so it's not possible to navigate to it

![image](https://user-images.githubusercontent.com/304126/128773774-7706607a-31cc-4de2-8e35-4630333d80de.png)

**Comment by chadell** [comment]
Fixed in #62
